routes/web.php
<?php

use App\Pemesanan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('konsumen', 'KonsumenController');
    Route::resource('user', 'UserController')->middleware('owner-only');
    Route::resource('produk', 'ProdukController');
    Route::resource('jenis_cetak', 'JenisCetakController');
    //pengeluaran    
    Route::resource('pengeluaran', 'PengeluaranController')->middleware('top-level');
    Route::get('modal-pengeluaran/{pemesanan_id}', 'PengeluaranController@modal')->name('pengeluaran.modal')->middleware('top-level');

    //pemesanan
    Route::resource('pemesanan', 'PemesananController');
    Route::post('proses-pemesanan', 'PemesananController@process')->name('pemesanan.process');
    Route::get('show-pemesanan', 'PemesananController@showAll')->name('pemesanan.show_all');
    Route::get('show-pemesanan/{status_pemesanan}', 'PemesananController@showPemesanan');
    Route::put('konfirmasi-pemesanan/{pemesanan_id}/{status}', 'PemesananController@changeStatus')->name('pemesanan.changeStatus');
    Route::get('cancel-pemesanan/{pemesanan_id}', 'PemesananController@cancel')->name('pemesanan.cancel');
    //pembayaran
    Route::get('pembayaran/{pemesanan_id}', 'PembayaranController@index')->name('pembayaran');
    Route::post('pembayaran/store/{pemesanan_id}', 'PembayaranController@store')->name('pembayaran.store');

    //penjualan
    Route::middleware('top-level')->group(function(){
        Route::get('laporan/penjualan', 'LaporanController@penjualan')->name('laporan.penjualan');
        Route::get('laporan/pengeluaran', 'LaporanController@pengeluaran')->name('laporan.pengeluaran');
        Route::get('laporan/laba-rugi', 'LaporanController@labaRugi')->name('laporan.laba-rugi');
    });

    //ubah password
    Route::get('ubah-password', 'ChangePasswordController@index')->name('ubah_password');
    Route::post('ubah-password/change', 'ChangePasswordController@change')->name('ubah_password.change');

});

 //tracking pesanan
 Route::post('/search', function(Request $request){
    $request->validate([
        'kode' => 'required'
    ]);

    $pemesanan = Pemesanan::where('kode', $request->kode)->first();
    if(!$pemesanan){
        return redirect()->back()->with('error', 'Invoice / Kode tidak ditemukan');
    } else {

        return view('tracking', compact('pemesanan'));
    }

})->name('search-pesanan');

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = 'produk';

    protected $fillable = [
        'nama_produk',
        'bahan_baku',
        'keterangan',
        'harga_satuan',
        'kategori'
    ];

    public static function getDefaultValues()
    {
        return (object) [
            'nama_produk' => '',
            'bahan_baku' => '',
            'keterangan' => '',
            'harga_satuan' => '',
            'kategori' => ''
        ];
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProdukRequest;
use Illuminate\Http\Request;
use App\Produk;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Produk::orderBy('nama_produk', 'asc')->get();
        return view('produk.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $produk = Produk::getDefaultValues();
        return view('produk.form', compact('produk'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdukRequest $request)
    {
        Produk::create($request->all());
        return redirect()->route('produk.index')->with('success', 'Berhasil menambah data produk');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produk = Produk::findOrFail($id);
        return view('produk.form', compact('produk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProdukRequest $request, $id)
    {
        Produk::find($id)->update($request->toArray());
        return redirect()->route('produk.index')->with('success', 'Berhasil menambah data produk');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Produk::find($id)->delete();
        return redirect()->route('produk.index')->with('success', 'Berhasil menghapus data produk');
    }
}

resources/views/produk/form.blade.php
@extends('layouts.app')

@section('title', 'Form Produk')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card">
                <div class="card-header">
                    Form Produk
                </div>
                <div class="card-body">
                    <form class="user" action="{{ (!isset($produk->id)) ?  route('produk.store') : route('produk.update', $produk->id) }}" method="post">
                        @csrf
        
                        @if(isset($produk->id))
                            @method('put')
                        @endif
        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Nama Produk</label>
                                <input type="text" class="form-control form-control-user" name="nama_produk" placeholder="Nama Produk" value="{{ old('nama_produk', $produk->nama_produk) }}">
                                @error('nama_produk')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Bahan Baku</label>
                                <input type="text" class="form-control form-control-user" name="bahan_baku"  placeholder="Bahan Baku" value="{{ old('bahan_baku', $produk->bahan_baku) }}">
                                @error('bahan_baku')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Harga</label>
                                <input type="number" class="form-control form-control-user" name="harga_satuan" placeholder="Harga" value="{{ old('harga_satuan', $produk->harga_satuan) }}">
                                @error('harga_satuan')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Kategori</label>
                                <select class="form-control" name="kategori" id="exampleFormControlSelect1">
                                    <option value="">Pilih Kategori</option>
                                    <option value="seragam" {{ (old('kategori') == 'seragam' || $produk->kategori == 'seragam') ? 'selected' : '' }}>Seragam</option>
                                    <option value="souvenir" {{ (old('kategori') == 'souvenir' || $produk->kategori == 'souvenir') ? 'selected' : '' }}>Souvenir</option>                                    
                                </select>
                                @error('kategori')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>                    
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 mb-2">
                                <label>Keterangan</label>
                                <textarea class="form-control" name="keterangan" placeholder="Keterangan">{{ old('keterangan', $produk->keterangan) }}</textarea>
                                @error('keterangan')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                                        
                        <button type="submit" class="btn btn-primary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Simpan</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/produk/index.blade.php
@extends('layouts.app')

@section('title', 'Data Produk')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <!-- Card -->
        <div class="card shadow mb-4">            
            <div class="card-body">
                <a href="{{ route('produk.create') }}" class="btn btn-primary mb-4"><i class="fa fa-plus"></i> Tambah</a>
                <table class="table table-striped" id="myTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama Produk</th>
                            <th>Bahan Baku</th>
                            <th>Harga</th>
                            <th>Kategori</th>
                            <th>Keterangan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama_produk }}</td>
                            <td>{{ $row->bahan_baku }}</td>
                            <td>{{ $row->harga_satuan }}</td>
                            <td>{{ $row->kategori }}</td>
                            <td>{{ $row->keterangan }}</td>
                            <td>
                                <form action="{{ route('produk.destroy', $row->id) }}" method="post">                                       
                                    <a href="{{ route('produk.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                    @csrf
                                    @method('delete')
                                    {{-- <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                        <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                        </span>
                                    </button> --}}
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>                
            </div>
        </div>
      </div>
    </div>

</div>
@endsection