routes/web.php
<?php

use App\Pemesanan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('konsumen', 'KonsumenController');
    Route::resource('user', 'UserController')->middleware('owner-only');
    Route::resource('produk', 'ProdukController');
    Route::resource('jenis_cetak', 'JenisCetakController');
    //pengeluaran    
    Route::resource('pengeluaran', 'PengeluaranController')->middleware('top-level');
    Route::get('modal-pengeluaran/{pemesanan_id}', 'PengeluaranController@modal')->name('pengeluaran.modal')->middleware('top-level');

    //pemesanan
    Route::resource('pemesanan', 'PemesananController');
    Route::post('proses-pemesanan', 'PemesananController@process')->name('pemesanan.process');
    Route::get('show-pemesanan', 'PemesananController@showAll')->name('pemesanan.show_all');
    Route::get('show-pemesanan/{status_pemesanan}', 'PemesananController@showPemesanan');
    Route::put('konfirmasi-pemesanan/{pemesanan_id}/{status}', 'PemesananController@changeStatus')->name('pemesanan.changeStatus');
    Route::get('cancel-pemesanan/{pemesanan_id}', 'PemesananController@cancel')->name('pemesanan.cancel');
    //pembayaran
    Route::get('pembayaran/{pemesanan_id}', 'PembayaranController@index')->name('pembayaran');
    Route::post('pembayaran/store/{pemesanan_id}', 'PembayaranController@store')->name('pembayaran.store');

    //penjualan
    Route::middleware('top-level')->group(function(){
        Route::get('laporan/penjualan', 'LaporanController@penjualan')->name('laporan.penjualan');
        Route::get('laporan/pengeluaran', 'LaporanController@pengeluaran')->name('laporan.pengeluaran');
        Route::get('laporan/laba-rugi', 'LaporanController@labaRugi')->name('laporan.laba-rugi');
    });

    //ubah password
    Route::get('ubah-password', 'ChangePasswordController@index')->name('ubah_password');
    Route::post('ubah-password/change', 'ChangePasswordController@change')->name('ubah_password.change');

});

 //tracking pesanan
 Route::post('/search', function(Request $request){
    $request->validate([
        'kode' => 'required'
    ]);

    $pemesanan = Pemesanan::where('kode', $request->kode)->first();
    if(!$pemesanan){
        return redirect()->back()->with('error', 'Invoice / Kode tidak ditemukan');
    } else {

        return view('tracking', compact('pemesanan'));
    }

})->name('search-pesanan');

app/Konsumen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Konsumen extends Model
{
    protected $table = 'konsumen';

    protected $fillable = [
        'nama_konsumen',
        'email',
        'instansi',
        'alamat',
        'no_telp',        
    ];


    public static function getDefaultValues()
    {
        return (object) [
            'nama_konsumen' => '',
            'email' => '',
            'instansi' => '',
            'alamat' => '',
            'no_telp' => '',
        ];
    }
}

app/Http/Controllers/KonsumenController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\KonsumenRequest;
use Illuminate\Http\Request;
use App\Konsumen;

class KonsumenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $konsumen = Konsumen::orderBy('nama_konsumen', 'asc')->get();
        return view('konsumen.index', compact('konsumen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $konsumen = Konsumen::getDefaultValues();
        return view('konsumen.form', compact('konsumen'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KonsumenRequest $request)
    {
        Konsumen::create($request->all());
        return redirect()->route('konsumen.index')->with('success', 'Berhasil menambah data konsumen');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $konsumen = Konsumen::find($id);
        return view('konsumen.form', compact('konsumen'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KonsumenRequest $request, $id)
    {
        $konsumen = Konsumen::find($id);

        $konsumen->update($request->all());

        return redirect()->route('konsumen.index')->with('success', 'Berhasil mengubah data konsumen');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $konsumen = Konsumen::find($id);

        $konsumen->delete();

        return redirect()->route('konsumen.index')->with('success', 'Berhasil menghapus data konsumen');
    }
}

resources/views/konsumen/form.blade.php
@extends('layouts.app')

@section('title', 'Konsumen')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card">
                <div class="card-header">
                    Form Konsumen
                </div>
                <div class="card-body">
                    <form class="user" action="{{ (!isset($konsumen->id)) ?  route('konsumen.store') : route('konsumen.update', $konsumen->id) }}" method="post">
                        @csrf
        
                        @if(isset($konsumen->id))
                            @method('put')
                        @endif
        
                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="nama_konsumen" placeholder="Nama Konsumen" value="{{ old('nama_konsumen', $konsumen->nama_konsumen) }}">
                                @error('nama_konsumen')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="instansi" id="lname" placeholder="Instansi" value="{{ old('instansi', $konsumen->instansi) }}">
                                @error('instansi')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="email" placeholder="Email" value="{{ old('email', $konsumen->email) }}">
                                @error('email')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <input type="number" class="form-control form-control-user" name="no_telp" placeholder="No. Telp" value="{{ old('no_telp', $konsumen->no_telp) }}">
                                @error('no_telp')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>                    
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <textarea name="alamat" class="form-control" placeholder="Alamat">{{ old('alamat', $konsumen->alamat) }}</textarea>
                            </div>
                        </div>
                    
                        <button type="submit" class="btn btn-primary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Save</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/konsumen/index.blade.php
@extends('layouts.app')

@section('title', 'Konsumen')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <!-- Card -->
        <div class="card shadow mb-4">            
            <div class="card-body">
                <a href="{{ route('konsumen.create') }}" class="btn btn-primary mb-4"><i class="fa fa-plus"></i> Tambah</a>
                <table class="table table-striped" id="myTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Instansi</th>
                            <th>Email</th>
                            <th>No Telp</th>
                            <th>Alamat</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($konsumen as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama_konsumen }}</td>
                            <td>{{ $row->instansi }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->no_telp }}</td>
                            <td>{{ $row->alamat }}</td>
                            <td>
                                <form action="{{ route('konsumen.destroy', $row->id) }}" method="post">                                       
                                    <a href="{{ route('konsumen.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                    @csrf
                                    @method('delete')
                                    {{-- <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                        <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                        </span>
                                    </button> --}}
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>                
            </div>
        </div>
      </div>
    </div>

</div>
@endsection