routes/web.php
<?php

use App\Pemesanan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('konsumen', 'KonsumenController');
    Route::resource('user', 'UserController')->middleware('owner-only');
    Route::resource('produk', 'ProdukController');
    Route::resource('jenis_cetak', 'JenisCetakController');
    //pengeluaran    
    Route::resource('pengeluaran', 'PengeluaranController')->middleware('top-level');
    Route::get('modal-pengeluaran/{pemesanan_id}', 'PengeluaranController@modal')->name('pengeluaran.modal')->middleware('top-level');

    //pemesanan
    Route::resource('pemesanan', 'PemesananController');
    Route::post('proses-pemesanan', 'PemesananController@process')->name('pemesanan.process');
    Route::get('show-pemesanan', 'PemesananController@showAll')->name('pemesanan.show_all');
    Route::get('show-pemesanan/{status_pemesanan}', 'PemesananController@showPemesanan');
    Route::put('konfirmasi-pemesanan/{pemesanan_id}/{status}', 'PemesananController@changeStatus')->name('pemesanan.changeStatus');
    Route::get('cancel-pemesanan/{pemesanan_id}', 'PemesananController@cancel')->name('pemesanan.cancel');
    //pembayaran
    Route::get('pembayaran/{pemesanan_id}', 'PembayaranController@index')->name('pembayaran');
    Route::post('pembayaran/store/{pemesanan_id}', 'PembayaranController@store')->name('pembayaran.store');

    //penjualan
    Route::middleware('top-level')->group(function(){
        Route::get('laporan/penjualan', 'LaporanController@penjualan')->name('laporan.penjualan');
        Route::get('laporan/pengeluaran', 'LaporanController@pengeluaran')->name('laporan.pengeluaran');
        Route::get('laporan/laba-rugi', 'LaporanController@labaRugi')->name('laporan.laba-rugi');
    });

    //ubah password
    Route::get('ubah-password', 'ChangePasswordController@index')->name('ubah_password');
    Route::post('ubah-password/change', 'ChangePasswordController@change')->name('ubah_password.change');

});

 //tracking pesanan
 Route::post('/search', function(Request $request){
    $request->validate([
        'kode' => 'required'
    ]);

    $pemesanan = Pemesanan::where('kode', $request->kode)->first();
    if(!$pemesanan){
        return redirect()->back()->with('error', 'Invoice / Kode tidak ditemukan');
    } else {

        return view('tracking', compact('pemesanan'));
    }

})->name('search-pesanan');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama', 'username', 'email', 'password', 'jabatan'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }


    public static function getDefaultValues()
    {
        return (object) [
            'nama' => '', 
            'username' => '', 
            'email' => '', 
            'password' => '', 
            'jabatan' => ''
        ];
    }

    public function getJabatan()
    {
        if($this->jabatan == 1){
            return 'Owner';
        } else if($this->jabatan == 2){
            return 'Finance';
        } else if($this->jabatan == 3){
            return 'CSA / Marketing';
        } else if ($this->jabatan == 4){
            return 'Produksi';
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('nama', 'asc')->get();
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = User::getDefaultValues();
        return view('user.form', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        User::create($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('user.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        User::find($id)->update($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form User')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card">
                <div class="card-header">
                    Form user
                </div>
                <div class="card-body">
                    <form class="user" action="{{ (!isset($user->id)) ?  route('user.store') : route('user.update', $user->id) }}" method="post">
                        @csrf
        
                        @if(isset($user->id))
                            @method('put')
                        @endif
        
                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="nama" placeholder="Nama User / Petugas" value="{{ old('nama', $user->nama) }}">
                                @error('nama')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="username"  placeholder="username" value="{{ old('username', $user->username) }}">
                                @error('username')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
        
                        <div class="form-group row">
                            <div class="col-sm-6 mb-2">
                                <input type="text" class="form-control form-control-user" name="email" placeholder="Email" value="{{ old('email', $user->email) }}">
                                @error('email')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col-sm-6 mb-2">
                                <select class="form-control" name="jabatan" id="exampleFormControlSelect1">
                                    <option>Jabatan</option>
                                    <option value="1" {{ (old('jabatan') == '1' || $user->jabatan == '1') ? 'selected' : '' }}>Owner</option>
                                    <option value="2" {{ (old('jabatan') == '2' || $user->jabatan == '2') ? 'selected' : '' }}>Finance</option>
                                    <option value="3" {{ (old('jabatan') == '3' || $user->jabatan == '3') ? 'selected' : '' }}>CSA / Marketing</option>
                                    <option value="4" {{ (old('jabatan') == '4' || $user->jabatan == '4') ? 'selected' : '' }}>Produksi</option>
                                </select>
                                @error('jabatan')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>                    
                        </div>
                        @if(!isset($user->id))                           
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <input type="password" name="password" class="form-control" placeholder="Password">
                                    @error('password')
                                        <span class="invalid-feedback d-block" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        @endif
                    
                        <button type="submit" class="btn btn-primary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-save"></i>
                            </span>
                            <span class="text">Save</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'User / Petugas')

@section('content')

<div class="container-fluid">
  
    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-12 mb-4">
        <!-- Card -->
        <div class="card shadow mb-4">            
            <div class="card-body">
                <a href="{{ route('user.create') }}" class="btn btn-primary mb-4"><i class="fa fa-plus"></i> Tambah</a>
                <table class="table table-striped" id="myTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Jabatan</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $row)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nama }}</td>
                            <td>{{ $row->username }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->getJabatan() }}</td>
                            <td>
                                <form action="{{ route('user.destroy', $row->id) }}" method="post">                                       
                                    <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning" title="Edit"><i class="fa fa-cog"></i></a>
                                    @csrf
                                    @method('delete')
                                    {{-- <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Yakin hapus data?')" >
                                        <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                        </span>
                                    </button> --}}
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>                
            </div>
        </div>
      </div>
    </div>

</div>
@endsection