routes/web.php
<?php

use App\Pemesanan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('konsumen', 'KonsumenController');
    Route::resource('user', 'UserController')->middleware('owner-only');
    Route::resource('produk', 'ProdukController');
    Route::resource('jenis_cetak', 'JenisCetakController');
    //pengeluaran    
    Route::resource('pengeluaran', 'PengeluaranController')->middleware('top-level');
    Route::get('modal-pengeluaran/{pemesanan_id}', 'PengeluaranController@modal')->name('pengeluaran.modal')->middleware('top-level');

    //pemesanan
    Route::resource('pemesanan', 'PemesananController');
    Route::post('proses-pemesanan', 'PemesananController@process')->name('pemesanan.process');
    Route::get('show-pemesanan', 'PemesananController@showAll')->name('pemesanan.show_all');
    Route::get('show-pemesanan/{status_pemesanan}', 'PemesananController@showPemesanan');
    Route::put('konfirmasi-pemesanan/{pemesanan_id}/{status}', 'PemesananController@changeStatus')->name('pemesanan.changeStatus');
    Route::get('cancel-pemesanan/{pemesanan_id}', 'PemesananController@cancel')->name('pemesanan.cancel');
    //pembayaran
    Route::get('pembayaran/{pemesanan_id}', 'PembayaranController@index')->name('pembayaran');
    Route::post('pembayaran/store/{pemesanan_id}', 'PembayaranController@store')->name('pembayaran.store');

    //penjualan
    Route::middleware('top-level')->group(function(){
        Route::get('laporan/penjualan', 'LaporanController@penjualan')->name('laporan.penjualan');
        Route::get('laporan/pengeluaran', 'LaporanController@pengeluaran')->name('laporan.pengeluaran');
        Route::get('laporan/laba-rugi', 'LaporanController@labaRugi')->name('laporan.laba-rugi');
    });

    //ubah password
    Route::get('ubah-password', 'ChangePasswordController@index')->name('ubah_password');
    Route::post('ubah-password/change', 'ChangePasswordController@change')->name('ubah_password.change');

});

 //tracking pesanan
 Route::post('/search', function(Request $request){
    $request->validate([
        'kode' => 'required'
    ]);

    $pemesanan = Pemesanan::where('kode', $request->kode)->first();
    if(!$pemesanan){
        return redirect()->back()->with('error', 'Invoice / Kode tidak ditemukan');
    } else {

        return view('tracking', compact('pemesanan'));
    }

})->name('search-pesanan');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title') - Sistem Manajemen Proyek CV. Cahaya Bintang
      Gemilang</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('css/sb-admin-2.css')}}" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

    <!-- Select2js -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />

</head>
<!-- Login Form if not authenticated -->
@guest 
  @yield('content')
@endguest

@auth
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
  
      <!-- Sidebar -->
      @include('layouts.sidebar')
      <!-- End of Sidebar -->
  
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
  
        <!-- Main Content -->
        <div id="content">
  
            <!-- Topbar -->
            @include('layouts.topbar')
            <!-- End of Topbar -->
  
            <!-- Begin Page Content -->
            @include('layouts.flash')

            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">@yield('title')</h1>
                </div>
            </div>

            @yield('content')
            
            <!-- /.container-fluid -->
  
        </div>
        <!-- End of Main Content -->
  
        <!-- Footer -->
        @include('layouts.footer')
        <!-- End of Footer -->
  
      </div>
      <!-- End of Content Wrapper -->
  
    </div>
    <!-- End of Page Wrapper -->
  
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  
    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
  
    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>


    <script>
      $(document).ready( function () {
          $('#myTable').DataTable();
          
          //select2 input option
          $('.mySelect').select2();
      } );
    </script>

    @stack('scripts')

  </body>
  @endauth
  
  </html>        

resources/views/layouts/flash.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">            
            @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show my-toast" role="alert">
                <strong>Success!</strong> {{ session()->get('success') }}.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif

            @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible fade show my-toast" role="alert">
                <strong>Error!</strong> {{ session()->get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
            @endif

            @if(session()->has('warning'))
            <div class="alert alert-warning alert-dismissible fade show my-toast" role="alert">
                <strong>Warning!</strong> {{ session()->get('warning') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span class="fa fa-times"></span>
                </button>
            </div>
            @endif         
        </div>
    </div>
</div>

resources/views/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; 2020 CV. Cahaya Bintang Gemilang.</span>
        </div>
    </div>
</footer>

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('dashboard')}}">
        
        <div class="sidebar-brand-text mx-3">Sistem Manajemen Proyek</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ (urlHasPrefix('dashboard') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ url('dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    @if(Auth::user()->jabatan != 4)
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="sidebar-heading">
        Master
    </div>

    <li class="nav-item {{ (urlHasPrefix('konsumen') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('konsumen.index') }}">
          <i class="fas fa-users"></i>
          <span>Konsumen / Customer</span></a>
    </li>
    @if(Auth::user()->jabatan == 1)
    <li class="nav-item {{ (urlHasPrefix('user') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('user.index') }}">
          <i class="fas fa-user-tie"></i>
          <span>User / Petugas</span></a>
    </li>
    @endif
    <li class="nav-item {{ (urlHasPrefix('produk') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('produk.index') }}">
          <i class="fas fa-box"></i>
          <span>Produk</span></a>
    </li>

    {{-- <li class="nav-item {{ (urlHasPrefix('jenis_cetak') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('jenis_cetak.index') }}">
          <i class="fas fa-print"></i>
          <span>Jenis Cetak</span></a>
    </li> --}}

    @endif

     <!-- Divider -->
     <hr class="sidebar-divider d-none d-md-block">
     <div class="sidebar-heading">
         Transaksi
     </div>

     @if(Auth::user()->jabatan == 1 || Auth::user()->jabatan == 2)
     {{-- <li class="nav-item link-pengeluaran {{ (urlHasPrefix('pengeluaran') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('pengeluaran.index') }}">
          <i class="fas fa-minus-square"></i>
          <span>Pengeluaran</span></a>
    </li> --}}
    @endif
    @if(Auth::user()->jabatan != 4)
    <li class="nav-item link-pemesanan {{ (urlHasPrefix('pemesanan') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('pemesanan.index') }}">
          <i class="fas fa-shopping-cart"></i>
          <span>Pemesanan</span></a>
    </li>
    @endif
    <li class="nav-item link-data-pemesanan {{ (urlHasPrefix('show-pemesanan') == true ) ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('pemesanan.show_all') }}" data-toggle="collapse" data-target="#collapseTwo">
          <i class="fas fa-dollar-sign"></i>
          <span>Data Pemesanan</span></a>
          
          <div id="collapseTwo" class="collapse {{ (urlHasPrefix('show-pemesanan') == true ) ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item {{ (urlHasPrefix('show-pemesanan/1') == true ) ? 'active' : '' }}" href="{{ url('show-pemesanan/1') }}">Pesanan Masuk</a>
                    <a class="collapse-item {{ (urlHasPrefix('show-pemesanan/2') == true ) ? 'active' : '' }}" href="{{ url('show-pemesanan/2') }}">Telah Dikonfirmasi</a>
                    <a class="collapse-item {{ (urlHasPrefix('show-pemesanan/3') == true ) ? 'active' : '' }}" href="{{ url('show-pemesanan/3') }}">Pemesanan Diproses</a>
                    <a class="collapse-item {{ (urlHasPrefix('show-pemesanan/4') == true ) ? 'active' : '' }}" href="{{ url('show-pemesanan/4') }}">Selesai dan Siap Diambil</a>
                    <a class="collapse-item {{ (urlHasPrefix('show-pemesanan/5') == true ) ? 'active' : '' }}" href="{{ url('show-pemesanan/5') }}">Pemesanan Telah Diambil</a>
                    <a class="collapse-item" href="{{ route('pemesanan.show_all') }}">Semua Pesanan</a>
                </div>
          </div>
    </li>

    @if(Auth::user()->jabatan == 1 || Auth::user()->jabatan == 2)
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="sidebar-heading">
        Laporan
    </div>

    <li class="nav-item link-pemesanan {{ (urlHasPrefix('penjualan') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('laporan.penjualan') }}">
          <i class="fas fa-file"></i>
          <span>Penjualan</span></a>
    </li>

    <li class="nav-item link-laporan-pengeluaran {{ (urlHasPrefix('pengeluaran') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('laporan.pengeluaran') }}">
          <i class="fas fa-file"></i>
          <span>Pengeluaran</span></a>
    </li>

    <li class="nav-item link-laba-rugi {{ (urlHasPrefix('laba-rugi') == true ) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('laporan.laba-rugi') }}">
          <i class="fas fa-file"></i>
          <span>Laba Rugi</span></a>
    </li>

    @endif

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

resources/views/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ ucwords(Auth::user()->nama) }}</span>               
                <img class="img-profile rounded-circle" src="{{ asset('img/default.png') }}" width="30" alt="img">               
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('ubah_password') }}">
                    <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                    Ubah Password
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yakin akan logout?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Klik "Logout" dibawah jika anda ingin melakukan logout dari sistem.</div>
            <div class="modal-footer">
                <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary" href="">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>